name: rss2discord

services:
  rss2discord:
    image: ghcr.io/delemangi/rss2discord:latest
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - CONFIG_PATH=/app/config/config.yaml
