name: Linters

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ruff:
    uses: Delemangi/.github/.github/workflows/ruff.yaml@main
    secrets: inherit

  mypy:
    uses: Delemangi/.github/.github/workflows/mypy.yaml@main
    secrets: inherit
