name: Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pytest:
    uses: Delemangi/.github/.github/workflows/pytest.yaml@main
